name: unmasker
description: Unmasker - Samsung Notes style app with mask/unmask tools, real-time sharing
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  intl: ^0.18.1
  path_provider: ^2.1.1
  uuid: ^4.2.1
  sqflite: ^2.3.0
  provider: ^6.1.1
  share_plus: ^7.2.1
  file_picker: ^6.1.1
  flutter_pdfview: ^1.3.2
  image_picker: ^1.0.5
  record: ^5.0.4
  audioplayers: ^5.2.1
  http: ^1.1.0
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true